/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagement;
import java.sql.*;
import javax.swing.ButtonGroup;
/**
 *
 * @author Cabuyao Col
 */
public class MyAccountDark extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Statement st;
    
    private String accName;

    /**
     * Creates new form accountSettings
     */
    public MyAccountDark() {
        initComponents();
//        checkConnections();
//        groupButton();
//        setFields();
        
        this.setLocationRelativeTo(null);
        
        normalClose.add(mainUI);
    }
    
//    public MyAccountDark(String userName){
//        initComponents();
//        checkConnections();
//        groupButton();
////        setFields();
//        
//        this.setLocationRelativeTo(null);
//        
//        this.accName = userName;
//        hideuname.setText(userName);
//        
//                try{
//            String sql1 = "SELECT * FROM Users WHERE username = '"+userName+"'";
//            rs = st.executeQuery(sql1);
//            
//            if(rs.next()){
//                uname.setText(rs.getString("username"));
//                upass.setText(rs.getString("upass"));
//                ufname.setText(rs.getString("ufname"));
//                ulname.setText(rs.getString("ulname"));
//                String gender = rs.getString("gender");
//                if(gender.equals("Female")){
//                    femaleB.doClick();
//                }
//                unum.setText(rs.getString("phone"));
//                uemail.setText(rs.getString("email"));
//            }
//            
////            String sql2 = "UPDATE Users SET username = '"+username+"'";
//        }
//        catch(SQLException e){
//            e.printStackTrace(System.err);
//        }
//    }
//    
//    public void checkConnections(){
//        try{
//            String db = "jdbc:ucanaccess://C:\\Users\\Cabuyao Col\\OneDrive\\Documents\\NetBeansProjects\\StockManagement\\Stock Management.accdb";
//            con=DriverManager.getConnection(db);
//            st = con.createStatement();
//        }
//        catch(SQLException e){
//            e.printStackTrace(System.err);
//        }
//    }
//    
//    private void groupButton(){
//        ButtonGroup bg = new ButtonGroup();
//        bg.add(maleB);
//        bg.add(femaleB);
//    }
//    
//    private void setFields(){
//        String userN = hideuname.getText();
//        String password = upass.getText().trim();
//        String firstname = ufname.getText().trim();
//                
//        try{
//            String sql1 = "SELECT * FROM Users WHERE username = '"+accName+"'";
//            rs = st.executeQuery(sql1);
//            
//            if(rs.next()){
//                String name = rs.getString("username");
//                uname.setText(name);
//                upass.setText(rs.getString("upass"));
//                ufname.setText(rs.getString("ufname"));
//                ulname.setText(rs.getString("ulname"));
//                String gender = rs.getString("gender");
//                if(gender.equals("Female")){
//                    femaleB.isSelected();
//                }
//                unum.setText(rs.getString("phone"));
//                uemail.setText(rs.getString("email"));
                
//            }
            
//            String sql2 = "UPDATE Users SET username = '"+username+"'";
//        }
//        catch(SQLException e){
//            e.printStackTrace(System.err);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainUI = new javax.swing.JLabel();
        normalClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        mainUI.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cabuyao Col\\Downloads\\Bryan\\uiSample.png")); // NOI18N

        normalClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Cabuyao Col\\Downloads\\Bryan\\Normal Close Button.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainUI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normalClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainUI)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(normalClose))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyAccountDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyAccountDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyAccountDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyAccountDark.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyAccountDark().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainUI;
    public javax.swing.JLabel normalClose;
    // End of variables declaration//GEN-END:variables
}
