/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmanagement;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.*;
/**
 *
 * @author Cabuyao Col
 */
public class Signup extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    ResultSet rs3;
    ResultSet rs4;
    
    public static final int PASSWORD_LENGTH = 8;

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
        connectionChecker();
        this.setLocationRelativeTo(null);
        
        ButtonGroup bg = new ButtonGroup();
        bg.add(rbMale);
        bg.add(rbFemale);
    }
    
    private void insertInfo(){
        String firstname = fname.getText().trim();
        String lastname = lname.getText().trim();
        String username = uname.getText().trim().replace(" ", "");
        String password = upass.getText().trim();
        String phonenum = upnum.getText().trim();
        String email = eAdd.getText().trim();
        String gender = "Male";
        String position = "Consumer";
        
        if(rbFemale.isSelected()){
            gender = "Female";
        }
        
        try{
            String sql2 = "INSERT INTO Users(username, upass, ufname, ulname, gender, phone, email, position) VALUES('"+username+"', '"+password+"', '"+firstname+"', '"+lastname+"', '"+gender+"', '"+phonenum+"', '"+email+"','"+position+"')";
            int i = st.executeUpdate(sql2);
            if(i>0){
                JOptionPane.showMessageDialog(null,"Your Account Has Been Created!");
                fname.setText(null);
                lname.setText(null);
                uname.setText(null);
                upass.setText(null);
                ucpass.setText(null);
                upnum.setText(null);
                eAdd.setText(null);
             }
            else{
                JOptionPane.showMessageDialog(null,"Please Check Your Information!");
            }
        }
        catch(SQLException c){
            c.printStackTrace(System.err);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tHeading1 = new javax.swing.JLabel();
        tHeading2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bHeading = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        lfname = new javax.swing.JLabel();
        llname = new javax.swing.JLabel();
        luname = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        lcpass = new javax.swing.JLabel();
        lpnum = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        uname = new javax.swing.JTextField();
        lgend = new javax.swing.JLabel();
        upnum = new javax.swing.JTextField();
        rspass = new javax.swing.JCheckBox();
        upass = new javax.swing.JPasswordField();
        ucpass = new javax.swing.JPasswordField();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        registerButton = new javax.swing.JButton();
        backLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        eAdd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(3, 127, 54));

        tHeading1.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        tHeading1.setForeground(new java.awt.Color(210, 180, 64));
        tHeading1.setText("VIAZONE");

        tHeading2.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        tHeading2.setForeground(new java.awt.Color(210, 180, 64));
        tHeading2.setText("TRADING");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(tHeading1)
                .addGap(32, 32, 32)
                .addComponent(tHeading2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tHeading2)
                    .addComponent(tHeading1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(3, 127, 54));

        bHeading.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        bHeading.setForeground(new java.awt.Color(210, 180, 64));
        bHeading.setText("    Hardware and Construction Supply");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(bHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bHeading)
                .addContainerGap())
        );

        Title.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        Title.setForeground(new java.awt.Color(199, 9, 9));
        Title.setText("Signup Consumer Account ");

        lfname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lfname.setForeground(new java.awt.Color(3, 127, 54));
        lfname.setText("First Name:");

        llname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        llname.setForeground(new java.awt.Color(3, 127, 54));
        llname.setText("Last Name:");

        luname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        luname.setForeground(new java.awt.Color(3, 127, 54));
        luname.setText("Username:");

        lpass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lpass.setForeground(new java.awt.Color(3, 127, 54));
        lpass.setText("Password:");

        lcpass.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lcpass.setForeground(new java.awt.Color(3, 127, 54));
        lcpass.setText("Confirm Password:");

        lpnum.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lpnum.setForeground(new java.awt.Color(3, 127, 54));
        lpnum.setText("Phone Number:");

        fname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        uname.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        lgend.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lgend.setForeground(new java.awt.Color(3, 127, 54));
        lgend.setText("Gender:");

        upnum.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        upnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                upnumKeyTyped(evt);
            }
        });

        rspass.setBackground(new java.awt.Color(255, 255, 255));
        rspass.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rspass.setText("Show Password");
        rspass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rspassActionPerformed(evt);
            }
        });

        upass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        upass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upassActionPerformed(evt);
            }
        });
        upass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                upassKeyTyped(evt);
            }
        });

        ucpass.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ucpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ucpassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ucpassKeyTyped(evt);
            }
        });

        rbMale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbMale.setSelected(true);
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rbFemale.setText("Female");
        rbFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemaleActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(3, 127, 54));
        registerButton.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        registerButton.setForeground(new java.awt.Color(204, 255, 102));
        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        backLogin.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        backLogin.setForeground(new java.awt.Color(199, 9, 9));
        backLogin.setText(">>Already have an account? LOGIN NOW!");
        backLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backLoginMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 127, 54));
        jLabel1.setText("Email Address:");

        eAdd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(llname)
                            .addComponent(lfname)
                            .addComponent(luname)
                            .addComponent(lpass)
                            .addComponent(lcpass)
                            .addComponent(lpnum)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rspass))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(eAdd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(upnum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(Title))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(registerButton))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lgend)
                        .addGap(18, 18, 18)
                        .addComponent(rbMale)
                        .addGap(31, 31, 31)
                        .addComponent(rbFemale)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lfname)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llname)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luname)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lpass)
                            .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lcpass)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(rspass)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(upnum, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lpnum))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgend)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addGap(30, 30, 30)
                .addComponent(registerButton)
                .addGap(18, 18, 18)
                .addComponent(backLogin)
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void backLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginMouseClicked
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backLoginMouseClicked

    private void backLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginMouseEntered
        backLogin.setForeground(new java.awt.Color(204, 255, 102));
    }//GEN-LAST:event_backLoginMouseEntered

    private void backLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLoginMouseExited
        backLogin.setForeground(new java.awt.Color(199, 9, 9));
    }//GEN-LAST:event_backLoginMouseExited

    private void rspassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rspassActionPerformed
        if(rspass.isSelected()){
            upass.setEchoChar((char)0);
            ucpass.setEchoChar((char)0);
        }
        else{
            upass.setEchoChar('*');
            ucpass.setEchoChar('*');
        }
    }//GEN-LAST:event_rspassActionPerformed

    private void upnumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upnumKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
        if (upnum.getText().length() == 11 ){
            evt.consume();
        }
    }//GEN-LAST:event_upnumKeyTyped
   
    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String username = uname.getText().trim().replace(" ", "");
        String email = eAdd.getText().trim();
        String phone = upnum.getText().trim();
        
        if(fieldsChecker()){
            if(!accountChecker(username)){
                if(!phoneNumberChecker(phone)){
                    if(!emailChecker(email)){
                        if(valEmail(email)){
                            insertInfo();
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Please enter a valid email address!");
                            eAdd.setText("");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void rbFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemaleActionPerformed

    private void upassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upassActionPerformed

    }//GEN-LAST:event_upassActionPerformed

    private void upassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_upassKeyTyped

    }//GEN-LAST:event_upassKeyTyped

    private void ucpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ucpassKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ucpassKeyPressed

    private void ucpassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ucpassKeyTyped

    }//GEN-LAST:event_ucpassKeyTyped

    private void clearFields(){
        String password = upass.getText().trim();
        String cpassword = ucpass.getText().trim();
        String username = uname.getText().trim();
        String phonenum = upnum.getText().trim();
        String email = eAdd.getText().trim();
        
        if(!password.equals(cpassword)){
            upass.setText(null);
            ucpass.setText(null);
        }
        else if(accountChecker(username)){
            uname.setText(null);
            upass.setText(null);
            ucpass.setText(null);
        }
        else if(phoneNumberChecker(phonenum)){
            upnum.setText(null);
        }   
        else if(emailChecker(email)){
            eAdd.setText(null);
        }
        else if(uname.getText().contains(" ")){
            uname.setText(null);
            upass.setText(null);
            ucpass.setText(null);
        }
        else if(upnum.getText().length() != 11){
            upnum.setText(null);
        }
        else if(upass.getText().length()<8){
            upass.setText(null);
            ucpass.setText(null);
        }
        else{
            fname.setText(null);
            lname.setText(null);
            uname.setText(null);
            upass.setText(null);
            ucpass.setText(null);
            upnum.setText(null);
        }
    }
    
    public boolean fieldsChecker(){
        String firstname = fname.getText().trim();
        String lastname = lname.getText().trim();
        String username = uname.getText().trim();
        String password = upass.getText().trim();
        String cpassword = ucpass.getText().trim();
        String phonenum = upnum.getText().trim();
        String email = eAdd.getText().trim();
        
        if(firstname.equals("") || lastname.equals("") || username.equals("") || password.equals("") || cpassword.equals("") || phonenum.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Some Fields are Empty", "Empty Fields", 2);
            return false;
        }
        else if(!password.equals(cpassword)){
            JOptionPane.showMessageDialog(rootPane, "Password does not match!", "Confirm Password", 2);
            clearFields();
            return false;
        }
        else if(accountChecker(username)){
            JOptionPane.showMessageDialog(rootPane, "This username already exist!", "Username Failed", 2);
            clearFields();
            return false;
        }
        else if(phoneNumberChecker(phonenum)){
            JOptionPane.showMessageDialog(rootPane, "This phone number already exist!", "Phone Failed", 2);
            clearFields();
            return false;
        }
        else if(emailChecker(email)){
            JOptionPane.showMessageDialog(rootPane, "This email already exist!", "Email Failed", 2);
            clearFields();
            return false;
        }
        else if(uname.getText().trim().contains(" ")){
            JOptionPane.showMessageDialog(rootPane, "No space is allowed in username!", "Username Failed", 2);
            clearFields();
            return false;
        }
        else if(upnum.getText().length() != 11){
            JOptionPane.showMessageDialog(rootPane, "Enter a valid phone number!", "ERROR!", 2);
            clearFields();
            return false;
        }
        else if(upass.getText().length()<8){
            JOptionPane.showMessageDialog(rootPane, "Password must be at least 8 characters!", "ERROR!", 2);
            clearFields();
            return false;
        }
        else{
            return true;
        }
    }
    
    public boolean accountChecker(String uname){
        boolean usernameExist = false;
        try{
            String sql1 = "SELECT * FROM Users WHERE username = '"+uname+"'";
            rs=st.executeQuery(sql1);
            
            if(rs.next()){
                usernameExist = true;
            }
        }
        catch(SQLException e){
            e.printStackTrace(System.err);
        }
        return usernameExist;
    }
    
    public boolean phoneNumberChecker(String phone){
        boolean phonenumExist = false;
        try{
            String sql1 = "SELECT * FROM Users WHERE phone = '"+phone+"'";
            rs3=st.executeQuery(sql1);
            
            if(rs3.next()){
                phonenumExist = true;
            }
        }
        catch(SQLException e){
            e.printStackTrace(System.err);
        }
        return phonenumExist;
    }
    
    public boolean emailChecker(String email){
        boolean emailExist = false;
        try{
            String sql1 = "SELECT * FROM Users WHERE email = '"+email+"'";
            rs4=st.executeQuery(sql1);
            
            if(rs4.next()){
                emailExist = true;
            }
        }
        catch(SQLException e){
            e.printStackTrace(System.err);
        }
        return emailExist;
    }
    
    private boolean valEmail(String acc){
        String emailCheck = "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$";
        Pattern ePat = Pattern.compile(emailCheck, Pattern.CASE_INSENSITIVE);
        Matcher matcher = ePat.matcher(acc);
        return matcher.find();
    }
    
    public static boolean is_Valid_Password(String password){
        int charCount = 0;
        int numCount = 0;
        
        if (password.length() < PASSWORD_LENGTH){
            return false;
        }
        
        for(int i = 0; i < password.length(); i++){
            char ch = password.charAt(i);

            if(is_Numeric(ch)){
                numCount++;
            }
            else if(is_Letter(ch)){
                charCount++;
            }
            else{
                return false;
            }
        }

        return (charCount >= 2 && numCount >= 2);
    }

    public static boolean is_Letter(char ch) {
        ch = Character.toUpperCase(ch);
        return (ch >= 'A' && ch <= 'Z');
    }

    public static boolean is_Numeric(char ch) {
        return (ch >= '0' && ch <= '9');
    }
    
    public void connectionChecker(){
        try{
            String db = "jdbc:ucanaccess://C:\\Users\\Admin\\Documents\\NetBeansProjects\\StockManagement\\Stock Management.accdb";
            con=DriverManager.getConnection(db);
            st = con.createStatement();
        }
        catch(SQLException e){
            e.printStackTrace(System.err);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Signup().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bHeading;
    private javax.swing.JLabel backLogin;
    private javax.swing.JTextField eAdd;
    private javax.swing.JTextField fname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lcpass;
    private javax.swing.JLabel lfname;
    private javax.swing.JLabel lgend;
    private javax.swing.JLabel llname;
    private javax.swing.JTextField lname;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel lpnum;
    private javax.swing.JLabel luname;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JButton registerButton;
    private javax.swing.JCheckBox rspass;
    private javax.swing.JLabel tHeading1;
    private javax.swing.JLabel tHeading2;
    private javax.swing.JPasswordField ucpass;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upass;
    private javax.swing.JTextField upnum;
    // End of variables declaration//GEN-END:variables
}
